[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "v4-core/=lib/v4-core/src/",
  "v4-periphery/=lib/v4-periphery/src/",
  "@uniswap/v4-core/=lib/v4-core/",
]
fs_permissions = [
  { access = "read-write", path = "./deployed-addresses.json" },
  { access = "read", path = "./usdc-addresses.json" },
  { access = "read", path = "./uniswap-v4-addresses.json" }
]

[profile.coverage]
skip = ["script"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
