[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-evm/contracts/",
    "@chainlink/contracts-ccip/=lib/chainlink-evm/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
